### ISSUE TITLE
undefined function: AppName.Repo.paginate/2

### ISSUE THREAD

**Issue by zaidakram** [drewolson/scrivener#14]
My Application's Repo looks like this
``` Elixir
defmodule AppName.Repo do
  use Ecto.Repo, otp_app: :app_name
  use Scrivener, page_size: 20
end
```

My index action looks like this...

``` Elixir
def index(conn, params) do
  words = from(w in Word, order_by: [asc: :abc_id], preload: [:languages]) 
    |> Repo.paginate(params)
  render(conn, "index.json",
    %{
      words: words.entries,
      current_page: words.page_number,
      total_pages: words.total_pages,
      per_page: words.page_size
    }
  )
end
```
Versions of other notable deps in mix file.
 
``` Elixir
  scrivener 1.0.0 
  phoenix 1.0.2 
  phoenix_ecto 1.2.0
  ecto 1.0.3
```

P.S: Scrivener.paginate/2 works with %Scrivener.Config.

**Comment by drewolson** [comment]
Hm, I'm not sure why you'd be seeing this. I have an example application using Scrivener with all the newest dependencies [here](https://github.com/drewolson/blox/tree/pagination). Perhaps you could take a look and see if you're doing something incorrectly?

**Comment by zaidakram** [comment]
And I've no idea why it has started working now. :angry:
