### ISSUE TITLE
Consider supporting tables without an id field

### ISSUE THREAD

**Issue by peck** [drewolson/scrivener#2]
Thanks for the code.

Was attempting to use to paginate a logs table I have that I'm ordering by timestamp but otherwise don't keep an ID. Perhaps consider allowing a configurable count field?

Thanks

**Comment by drewolson** [comment]
Sorry to have let this sit for so long. This is a good idea, I'll experiment with allowing the field to be configurable. If you're got more specific ideas, I'd love a PR.

**Comment by eikes** [comment]
Here is a PR for that: https://github.com/drewolson/scrivener/pull/6

**Comment by drewolson** [comment]
Close thanks to #6.
