### ISSUE TITLE
Add ecto 1.1.0 support

### ISSUE THREAD

**Issue by TakteS** [drewolson/scrivener#21]
The upgrade to new phoenix (1.1) fails with error:

Looking up alternatives for conflicting requirements on postgrex
  Activated version: 0.9.1
  From mix.exs: >= 0.0.0
  From ecto v1.1.0: ~> 0.10
  From scrivener v1.1.0: ~> 0.9.0

** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies

**Comment by drewolson** [comment]
@TakteS I actually just upgraded Scrivener to 1.1.1 to fix this issue. Please trying using `1.1.1` and let me know if it is still a problem.

**Comment by TakteS** [comment]
Ok, I'll try

**Comment by TakteS** [comment]
Yah. This helped. Update version to in the your README.md in the installation section :)

**Comment by drewolson** [comment]
The version in the README uses the pessimistic operator `~> 1.0` and would pick up this new version. I'm going to go ahead and close this issue. Thanks!
