### ISSUE TITLE
module Scrivener is not loaded could not be found

### ISSUE THREAD

**Issue by debonair** [drewolson/scrivener#24]
When in Add 
```elixir
use Scrivener, page_size: 10
```
to my repo I get the error

module Scrivener is not loaded could not be found, even after fetching the dependencies. I am using the latest phoenix for my project

**Comment by drewolson** [comment]
This seems like you're generally having a problem loading your dependencies. I have several applications using scrivener and this isn't a problem. If you're able to provide some more information I may be able to help, but until them I'm closing this issue.

**Comment by DavidRawk-Blake** [comment]
I fixed this by running `mix deps.compile`
