### ISSUE TITLE
Feature request: Return total entries count

### ISSUE THREAD

**Issue by danmcclain** [drewolson/scrivener#3]
Since you already need to retrieve the count of entries to get the total number of pages, it would be beneficial to add it to the `Page` struct so the user doesn't need to retrieve it again

**Comment by drewolson** [comment]
I'll add this tonight, thanks!

**Comment by danmcclain** [comment]
I would have made a PR, just been slammed lately. Thanks!

**Comment by drewolson** [comment]
Added and released.
