### ISSUE TITLE
Ecto 2.0 support

### ISSUE THREAD

**Issue by bjz** [drewolson/scrivener#35]
The [Ecto 2.0.0-rc is out](http://blog.plataformatec.com.br/2016/04/ecto-2-0-0-rc-is-out/). Are there any plans to get scrivener working with the new version? I've noticed that ja_serializer depends on Scrivener also updating, (see AgilionApps/ja_serializer#112). Not sure what your plans are for the transition.

**Comment by drewolson** [comment]
See #36
