### ISSUE TITLE
Provide show_totals option in Config for unbounded data

### ISSUE THREAD

**Issue by joeyrosztoczy** [drewolson/scrivener#45]
Hey man! Hope things are good!

I'm running a local fork of Scrivener/Scrivener_Ecto right now that adds a ```show_totals: boolean``` field to the Config struct.

The default is true, since I only turn it off for certain tables.

The use case is when working with unbounded data (like a sensor reading table in postgres, or gps points, etc), calculating the totals can cause DB timeouts.

In particular, I think pagination has really nice use cases w/ the new Flow module for processing large sets of data.

If you like the idea, I can submit a PR w/ tests to the repos monday! Let me know. Scrivener is solid by the way, thanks for creating it!

**Comment by drewolson** [comment]
@joeyrosztoczy as long as this can be done in a backwards compatible manner I'd be happy to see a PR. Thanks!

**Comment by drewolson** [comment]
Please use `options` (added in `2.2.0`).
