### ISSUE TITLE
Provide max_number_pages option in Config

### ISSUE THREAD

**Issue by miskolc** [drewolson/scrivener#47]
I've detailed the problem at the Scrivener Elastic project [here] (https://github.com/radar/scrivener_elastic/issues/1)

Basically I want to add a new field to the Config struct. If it's not set, it will return all the pages found( can be a large number ie 1_000_000). If it's set then it will show only the first max_number_of_pages pages.
Can we add this field it to Scrivener.Config?

I've also noticed this [open issue](https://github.com/drewolson/scrivener/issues/45) that is a bit similar to my situation but it's for `Scrivener Ecto` use case. Maybe we can find a way to avoid this types of issues in the future, since you need to change the `Scrivener.Config` every time you need a new field for a package that just happens to use Scrivener. 
Maybe a `:options`/`:custom_options` field that can hold custom parameters will do the trick. In this way we won't need to create extra fields in Scrivener for each use case and keep the package as slim and general as possible.

**Comment by drewolson** [comment]
@miskolc `:options` is a great idea! I'll look into it this weekend.

**Comment by miskolc** [comment]
@drewolson Awesome. Please let me know when you make a decision.

**Comment by miskolc** [comment]
Hi Drew! Did you find the time to contemplate on the `:options` feature?

**Comment by drewolson** [comment]
Not yet, but I still plan on it.

**Comment by drewolson** [comment]
I added `options` in `2.2.0`.
