### ISSUE TITLE
Q: Handling large number of pages?

### ISSUE THREAD

**Issue by elvanja** [drewolson/scrivener#48]
I have a case where the number of records is relatively large, so it produces e.g. 50+ pages. This cases a bit of an issue with UI since those pages don't fit the page nicely (break into multiple rows etc.).

For [kaminari](https://github.com/kaminari/kaminari) for example, this is configurable (even has default behavior) via various `window` related params. So, is there a way to achieve the same for scrivener?

If not, would there be interest in adding this to scrivener or do you prefer to leave it to the consumers?

Thank you for your time 😄 

P.S. If there'd be interest in adopting this for scrivener, I have to solve this for a project, might ask the owner to devote some time to add this to scrivener so I might help.

**Comment by drewolson** [comment]
@elvanja scrivener remains agnostic about how you choose to display the page information in a UI. If you're interested in a project focused on that, please see [scrivener_list](https://github.com/stephenmoloney/scrivener_list).

**Comment by elvanja** [comment]
Excellent. Thank you @drewolson!

**Comment by elvanja** [comment]
Just a small update, there is the https://github.com/mgwidmann/scrivener_html project that does exactly this.
