### ISSUE TITLE
Option to disable pagination when results are on single page

### ISSUE THREAD

**Issue by ArturT** [drewolson/scrivener#52]
Would be great to have an option to don't show the pagination when there is only 1 page with results.

**Comment by drewolson** [comment]
I'm not sure what you mean by this. If you're suggesting that we should return the raw result set rather than a `Scrivener.Page` if the result is a single page, that's not something I'll consider. We want consistent return values from the `paginate` call.

**Comment by ArturT** [comment]
I meant when I do 
```
<%= pagination_links @page, hide_when_single_page: true %>
```
it would render nothing.

**Comment by ArturT** [comment]
I moved this issue to the proper repo https://github.com/mgwidmann/scrivener_html/issues/65
