### ISSUE TITLE
dialyzer error - can't decipher

### ISSUE THREAD

**Issue by tiotolstoy** [drewolson/scrivener#62]
Having issues with one of my functions because I try to do `.entries` on a Scrivener map. Any ideas what the below means? Any help at all is absolutely appreciated.
```
          #{'entries' := __@1} can never match the type 
```

A little bit more info about what I'm doing is here. https://elixirforum.com/t/handle-adding-fields-into-map/31846

**Comment by drewolson** [comment]
Unfortunately I don't know a ton about dialyzer at all. I could use some help adding / fixing specs to scrivener from people who do know more. In the meantime I'd suggest adding this to your ignored errors.
