### ISSUE TITLE
Help with maintenance of the `Scrivener.HTML` project?

### ISSUE THREAD

**Issue by kenny-evitt** [drewolson/scrivener#68]
Please let me know if this isn't the appropriate venue – or just close the issue :) – I also noticed that this project itself is in 'low maintenance mode', so no worries if this isn't something you'd be interested in in helping out with.

`Scrivener.HTML` seems to be un-maintained; see:

- [Maintenance Help · Issue #103 · mgwidmann/scrivener_html](https://github.com/mgwidmann/scrivener_html/issues/103)

Several users of that library have contributed changes to resolve some issues, mainly due to dependency conflicts as various other libraries have been updated. I think most of the desired changes are literally just fiddling with dependency versions, e.g. relaxing version requirements.

Unfortunately, the owner of that project/package doesn't seem able or willing to follow-up on any of the open issues. (And that's totally okay!) But perhaps you, the creator/owner/maintainer and various contributors to this project, might be able to contact the creator/owner of `Scrivener.HTML` yourself and ask them to consider transferring ownership of the project to someone else. (And it's totally fine if no one has the time, or wants to spend it, to do any of that.)

Worst case, the users of this library can always fork it themselves – several have done so already.

Maybe second-best case would be someone stepping up to maintain a fork. That seems like it would also require changing the project/package name (e.g. on Hex).

Thanks for the project!

**Comment by thbar** [comment]
(this is a follow-up of discussion on the [Elixir forum](https://elixirforum.com/t/call-for-help-on-scrivener-html-maintenance-can-anyone-reach-matt-widmann/42526))

Just commenting that there are at least two coins to this: the GitHub repo (forking and consolidating on someone's fork can be done reasonably) and the Hex package.

For the Hex package, here are useful links:
- https://hexdocs.pm/hex/Mix.Tasks.Hex.Owner.html#module-transfer-ownership (for full transfer)
- https://hexdocs.pm/hex/Mix.Tasks.Hex.Owner.html#module-add-owner (for shared owner)

There have been instances where the transfer wasn't straightforward at least for some party (e.g. https://github.com/mochi/mochiweb/issues/233).

I hope we'll be able to keep the package name for clarity. It also seems like a form of "community cleverness", if we can collectively achieve this.

**Comment by drewolson** [comment]
Thanks for opening the issue. I'm not actively doing Elixir development these days and I don't have time to get involved in the ownership transfer of this library. That said, if you all do end up transferring it, please open a PR to change the link on the `README` and I'd be happy to merge it.

**Comment by kenny-evitt** [comment]
@drewolson Thanks!
